### ISSUE TITLE
Dopolni README.md

### ISSUE THREAD

**Issue by bbYYJnhA** [bbYYJnhA/Wu-Zi-Qi#1]
Dopolni opis, dodaj pravila igre ter tehnične podrobnosti o programu. Dodaj tudi kakšno slikico.

**Comment by markbaltic** [comment]
Opis dodan, pravila napisana. Tehnične podrobnosti bova dodala na koncu (ko bo program že napisan), sliko bova dodala tudi na koncu (bova prikazala, kako najina igra izgleda).

**Comment by bbYYJnhA** [comment]
Tole je nasvet s foruma na učilnici PRG2, ki ga je modro upoštevati za naslednjič ko zapiraš issue.

> Recimo, da imate odprt issue številka 42. Recimo, da naredite commit, v katerem popravite napako, ki jo opisuje issue 42. Potem je napačna procedura naslednja:
> 1. Naredite commit z opisom, recimo "Dodal opis igrice v README.md"
> 2. Naredite push commita na GitHub.
> 3. Na GitHubu ročno zaprete issue 42.
> 
> Problem je v tem, da se v issue ne vidi, s katerim commit-om je bil issue odpravljen. GitHub omogoča, da v opisu commita poveste, da z njim zapirate dani issue. Pravilna procedura:
> 1. Naredite commit z opisom "Dodaj opis igrice v README.md, close #42".
> 2. Naredite push.
> 
> S tem boste issue avtomatično zaprli in ostali bodo videli, kateri commit ga je zaprl. Pa še to, opise commitov se splača pisati v velelniku:
> - Dodal opis igrice v README --> Dodaj opis igrice v README
> - Napaka pri premiku laserja odpravljena --> Odpravi napako pri premiku laserja, close #23
> - Osnovna struktura razredov --> Nastavi ogrodje za osnovno strukturo razredov
> 
> Ko pregledujete commit log, je dosti lažje razumeti sporočila napisana v velelniku.
