### ISSUE TITLE
Preglej časovni in dopolni vsebinski načrt

### ISSUE THREAD

**Issue by bbYYJnhA** [bbYYJnhA/Wu-Zi-Qi#2]
Pod vsebinski načrt se šteje tudi, če odpreš tudi kak now issue.

**Comment by bbYYJnhA** [comment]
Predlagam da se časovni in vsebinski načrt dela na wiki vsebinski-nacrt.md ter casovni-nacrt.md pa se izbriše.

**Comment by markbaltic** [comment]
Se strinjam, da te stvari urejava na wiki. Sem pregledal in dopolnil.
