### ISSUE TITLE
Načrtuj grafični vmesnik

### ISSUE THREAD

**Issue by bbYYJnhA** [bbYYJnhA/Wu-Zi-Qi#3]
Spodaj je primer igralne plošče. Potrebno jo je še oblikovati in določiti pozicijo gumbov. Po potrebi se lahko predloga igralne plošče zamenja in uskladi z gumbi. 
![renjugame](https://cloud.githubusercontent.com/assets/16720601/13333260/6d89fbca-dc06-11e5-8c72-ddc1c7582d15.jpg)
Predlagam gumbe:
- razveljavi potezo
- nova igra
- izberi težavnost (opcijsko)

Mogoče dodamo tudi uro, ki odšteva čas igranja.

**Comment by markbaltic** [comment]
Je smiselno igralca prisilit k hitri igri s pomočjo omejitve časa igranja?

**Comment by bbYYJnhA** [comment]
Potem bi bila to tudi omejitev za računalnik, kar pa bi lahko pomenilo da bi se računalnik odločal zelo slabo. Če bova imela popolno kontrolo nad časom igranja računalnika je to možno, ne vem pa če nujno potrebno.
