### ISSUE TITLE
Naredi metodo self.stanje

### ISSUE THREAD

**Issue by bbYYJnhA** [bbYYJnhA/Wu-Zi-Qi#8]
Metoda self.stanje naj prikazuje "trenutno stanje" igre. self.stanje naj se po vsaki potezi spremeni in prikaže na zaslonu. Predlagam 5 možnosti:
- na potezi je črni/beli
- črni/beli je zmagal
- igra je neodločena

**Comment by bbYYJnhA** [comment]
Zadeva je trenutno na pol rešena v gui. To metodo potrebujeva le zaradi napisa.

**Comment by markbaltic** [comment]
Mislim, da sva to težavo že odpravila.
